-- 1. Salary Components Table (급여 항목)
create table public.salary_components (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('allowance', 'deduction')),
  is_taxable boolean default true,
  is_fixed boolean default true,
  default_amount numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default Korean payroll components
insert into public.salary_components (name, type, is_taxable, is_fixed, default_amount) values
('기본급', 'allowance', true, true, 0),
('직책수당', 'allowance', true, true, 0),
('연장근로수당', 'allowance', true, false, 0),
('주휴수당', 'allowance', true, false, 0),
('기본휴일수당', 'allowance', true, false, 0),
('교통비', 'allowance', false, true, 0), -- 비과세 한도 체크 필요하지만 일단 비과세로
('식대', 'allowance', false, true, 100000), -- 비과세
('상여금', 'allowance', true, false, 0),
('국민연금', 'deduction', false, false, 0),
('건강보험', 'deduction', false, false, 0),
('장기요양보험', 'deduction', false, false, 0),
('고용보험', 'deduction', false, false, 0),
('소득세', 'deduction', false, false, 0),
('지방소득세', 'deduction', false, false, 0);

-- 2. Employee Salary Settings Table (직원별 급여 설정)
create table public.employee_salary_settings (
  id bigint generated by default as identity primary key,
  employee_id bigint references public.employees(id) on delete cascade,
  component_id bigint references public.salary_components(id) on delete cascade,
  amount numeric default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(employee_id, component_id)
);

-- 3. Payroll Records Table (월별 급여 대장)
create table public.payroll_records (
  id bigint generated by default as identity primary key,
  employee_id bigint references public.employees(id) on delete cascade,
  year integer not null,
  month integer not null,
  total_allowance numeric default 0,
  total_deduction numeric default 0,
  net_pay numeric default 0,
  finalized_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Payroll Items Table (급여 상세 내역)
create table public.payroll_items (
  id bigint generated by default as identity primary key,
  payroll_id bigint references public.payroll_records(id) on delete cascade,
  component_id bigint references public.salary_components(id) on delete cascade,
  amount numeric default 0
);

-- Enable RLS
alter table public.salary_components enable row level security;
alter table public.employee_salary_settings enable row level security;
alter table public.payroll_records enable row level security;
alter table public.payroll_items enable row level security;

-- Policies (Allow all for authenticated users for now)
create policy "Enable all access for authenticated users" on public.salary_components for all using (auth.role() = 'authenticated');
create policy "Enable all access for authenticated users" on public.employee_salary_settings for all using (auth.role() = 'authenticated');
create policy "Enable all access for authenticated users" on public.payroll_records for all using (auth.role() = 'authenticated');
create policy "Enable all access for authenticated users" on public.payroll_items for all using (auth.role() = 'authenticated');
