-- Enable UUID extension (optional but good practice)
create extension if not exists "uuid-ossp";

-- 1. Employees Table
create table public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  position text not null,
  base_salary numeric default 0,
  store_name text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Settings Table
create table public.settings (
  id bigint generated by default as identity primary key,
  stores jsonb default '[]'::jsonb,
  thresholds jsonb default '{}'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default settings row (ID=1)
insert into public.settings (id, stores, thresholds)
values (1, '[]'::jsonb, '{}'::jsonb);

-- 3. Monthly Records Table
create table public.monthly_records (
  id bigint generated by default as identity primary key,
  year integer not null,
  month integer not null,
  total_revenue numeric default 0,
  total_incentive numeric default 0,
  total_profit numeric default 0,
  employee_count integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Incentive Details Table
create table public.incentive_details (
  id bigint generated by default as identity primary key,
  record_id bigint references public.monthly_records(id) on delete cascade,
  employee_name text not null,
  position text,
  store_name text,
  net_sales numeric default 0,
  profit_margin numeric default 0,
  incentive_amount numeric default 0,
  level integer default 0,
  multiplier numeric default 0
);

-- 5. Enable Row Level Security (RLS) - Optional for now, but good for future
-- For simplicity in this initial setup, we will allow public access or authenticated access.
-- Since we implemented login, let's allow access to authenticated users.

alter table public.employees enable row level security;
alter table public.settings enable row level security;
alter table public.monthly_records enable row level security;
alter table public.incentive_details enable row level security;

-- Policy: Allow everything for authenticated users (Simple setup)
create policy "Enable all access for authenticated users" on public.employees
  for all using (auth.role() = 'authenticated');

create policy "Enable all access for authenticated users" on public.settings
  for all using (auth.role() = 'authenticated');

create policy "Enable all access for authenticated users" on public.monthly_records
  for all using (auth.role() = 'authenticated');

create policy "Enable all access for authenticated users" on public.incentive_details
  for all using (auth.role() = 'authenticated');

-- IMPORTANT: For the very first login/signup to work easily without RLS blocking, 
-- you might want to temporarily allow anon access OR just ensure you sign up first.
-- Let's add a policy for anon read access just in case, or keep it strict.
-- We will stick to authenticated access.
