-- Work Types Table (근무 형태 설정)
create table public.work_types (
  id bigint generated by default as identity primary key,
  name text not null,
  days_per_week numeric not null default 5,
  basic_daily_hours numeric not null default 8,
  overtime_daily_hours numeric not null default 0,
  overtime_days_per_week numeric not null default 0,
  holiday_work_daily_hours numeric not null default 0,
  holiday_work_days_per_week numeric not null default 0,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.work_types enable row level security;

-- Policies
create policy "Enable all access for authenticated users" on public.work_types for all using (auth.role() = 'authenticated');

-- Insert default work types
insert into public.work_types (name, days_per_week, basic_daily_hours, overtime_daily_hours, overtime_days_per_week, holiday_work_daily_hours, holiday_work_days_per_week, description) values
('주 5일 (기본)', 5, 8, 0, 0, 0, 0, '일 8시간, 주 5일 근무'),
('주 6일 (연장 포함)', 5, 8, 0.8, 5, 7.5, 1, '일 8시간+연장, 주 6일 근무 (토요일 휴일근로)');
